# Generated by Django 5.0.2 on 2024-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('stock_code', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('weight_per_metre', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
