# Generated by Django 5.0.2 on 2024-07-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
    ]
