# Generated by Django 5.0.2 on 2024-07-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0003_rename_first_name_driver_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='username',
            new_name='employee_number',
        ),
    ]
