# Generated by Django 5.0.2 on 2024-08-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
