# Generated by Django 5.0.2 on 2024-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metres',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
