# Generated by Django 5.0.2 on 2024-07-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DLMS', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('day', models.CharField(max_length=10)),
                ('description', models.CharField(choices=[('Pick-up', 'Pick-up'), ('Delivery', 'Delivery'), ('Sale Trip', 'Sale Trip')], max_length=20)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('est_distance', models.CharField(max_length=100)),
                ('co_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLMS.codriver')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLMS.driver')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLMS.product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLMS.vehicle')),
            ],
        ),
    ]
