# Generated by Django 5.0.2 on 2024-07-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='product',
        ),
    ]
