# Generated by Django 5.0.2 on 2024-07-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0003_loadtrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadTrip',
        ),
    ]
