# Generated by Django 5.0.2 on 2024-07-22 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0002_product'),
        ('DTMS', '0004_delete_loadtrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('pieces', 'Pieces'), ('rolls', 'Rolls')], max_length=10)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLMS.product')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DTMS.trip')),
            ],
        ),
    ]
