# Generated by Django 5.0.2 on 2024-07-24 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0006_alter_loadtrip_total_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co_driver_name', models.CharField(max_length=100)),
                ('co_driver_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DTMS.trip')),
            ],
        ),
    ]
