# Generated by Django 5.0.2 on 2024-07-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0007_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='driver_name',
            new_name='driver_first_name',
        ),
    ]
