# Generated by Django 5.0.2 on 2024-07-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0008_rename_driver_name_expense_driver_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='driver_first_name',
            new_name='driver_full_name',
        ),
    ]
