# Generated by Django 5.0.2 on 2024-07-25 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0009_rename_driver_first_name_expense_driver_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='co_driver_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='co_driver_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='driver_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='driver_full_name',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vehicle_reg_no',
        ),
        migrations.AddField(
            model_name='expense',
            name='co_driver_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='driver_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DTMS.trip'),
        ),
    ]
