# Generated by Django 5.0.2 on 2024-07-25 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0010_remove_expense_co_driver_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co_driver_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DTMS.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
