# Generated by Django 5.0.2 on 2024-07-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0011_expenses_delete_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_consumed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DTMS.trip')),
            ],
        ),
    ]
