# Generated by Django 5.0.2 on 2024-07-26 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0012_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
