# Generated by Django 5.0.2 on 2024-07-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0015_stop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
