# Generated by Django 5.0.2 on 2024-08-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0006_delete_customuser'),
        ('DTMS', '0017_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLMS.vehicle'),
        ),
    ]
