# Generated by Django 5.0.2 on 2024-08-07 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0006_delete_customuser'),
        ('DTMS', '0018_alter_garage_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provider', models.CharField(max_length=100)),
                ('maintenance_date', models.DateField()),
                ('inspection_date', models.DateField()),
                ('insurance_date', models.DateField()),
                ('speed_governor_date', models.DateField()),
                ('kenha_permit_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLMS.vehicle')),
            ],
        ),
    ]
