# Generated by Django 5.0.2 on 2024-08-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0019_maintenanceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='stops',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
