# Generated by Django 5.0.2 on 2024-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0006_delete_customuser'),
        ('DTMS', '0020_trip_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='stops',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='loadtrip',
            unique_together={('trip', 'product')},
        ),
    ]
