# Generated by Django 5.0.2 on 2024-08-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0021_alter_trip_stops_alter_loadtrip_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loadtrip',
            unique_together=set(),
        ),
    ]
