# Generated by Django 5.0.2 on 2024-08-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0006_delete_customuser'),
        ('DTMS', '0022_alter_loadtrip_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadtrip',
            name='product',
        ),
        migrations.RemoveField(
            model_name='loadtrip',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='loadtrip',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='loadtrip',
            name='type',
        ),
        migrations.CreateModel(
            name='LoadTripProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DTMS.loadtrip')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLMS.product')),
            ],
        ),
        migrations.AddField(
            model_name='loadtrip',
            name='products',
            field=models.ManyToManyField(through='DTMS.LoadTripProduct', to='DLMS.product'),
        ),
    ]
