# Generated by Django 5.0.2 on 2024-08-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0023_remove_loadtrip_product_remove_loadtrip_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('ended', 'Ended')], default='ongoing', max_length=10),
        ),
    ]
