# Generated by Django 5.0.2 on 2024-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0024_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
