# Generated by Django 5.0.2 on 2024-09-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0026_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='actual_distance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_odometer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_odometer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
