# Generated by Django 5.0.2 on 2024-09-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0027_trip_actual_distance_trip_end_odometer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
