# Generated by Django 5.0.2 on 2024-09-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0029_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='track_solid_date',
            field=models.DateField(null=True),
        ),
    ]
