# Generated by Django 5.0.2 on 2024-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0030_maintenanceschedule_track_solid_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.AddField(
            model_name='garage',
            name='garage_expense',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
