# Generated by Django 5.0.2 on 2024-09-12 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTMS', '0031_delete_software_garage_garage_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtripproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
