# Generated by Django 5.0.2 on 2024-09-13 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLMS', '0009_product_metres'),
        ('DTMS', '0032_loadtripproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadtripproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='co_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DLMS.codriver'),
        ),
    ]
